<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="2" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-23T07:32:41Z" name="Suite" finished-at="2023-04-23T07:32:46Z" duration-ms="5418">
    <groups>
    </groups>
    <test started-at="2023-04-23T07:32:41Z" name="Test" finished-at="2023-04-23T07:32:46Z" duration-ms="5418">
      <class name="testcases.TC001_logintest">
        <test-method is-config="true" signature="ExcelSetup()[pri:0, instance:testcases.TC001_logintest@3697186]" started-at="2023-04-23T07:32:40Z" name="ExcelSetup" finished-at="2023-04-23T07:32:41Z" duration-ms="250" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ExcelSetup -->
        <test-method is-config="true" signature="SetUp(java.lang.reflect.Method)[pri:0, instance:testcases.TC001_logintest@3697186]" started-at="2023-04-23T07:32:41Z" name="SetUp" finished-at="2023-04-23T07:32:43Z" duration-ms="2087" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases.TC001_logintest.InvalidLogin() throws com.codoid.products.exception.FilloException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="InvalidLogin()[pri:0, instance:testcases.TC001_logintest@3697186]" started-at="2023-04-23T07:32:43Z" name="InvalidLogin" finished-at="2023-04-23T07:32:43Z" duration-ms="740" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidLogin -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:testcases.TC001_logintest@3697186]" started-at="2023-04-23T07:32:43Z" name="TearDown" finished-at="2023-04-23T07:32:44Z" duration-ms="306" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="SetUp(java.lang.reflect.Method)[pri:0, instance:testcases.TC001_logintest@3697186]" started-at="2023-04-23T07:32:44Z" name="SetUp" finished-at="2023-04-23T07:32:46Z" duration-ms="1810" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases.TC001_logintest.valid_login() throws java.lang.InterruptedException,com.codoid.products.exception.FilloException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="valid_login()[pri:0, instance:testcases.TC001_logintest@3697186]" started-at="2023-04-23T07:32:46Z" name="valid_login" finished-at="2023-04-23T07:32:46Z" duration-ms="186" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- valid_login -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:testcases.TC001_logintest@3697186]" started-at="2023-04-23T07:32:46Z" name="TearDown" finished-at="2023-04-23T07:32:46Z" duration-ms="278" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- testcases.TC001_logintest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
